### ISSUE TITLE
Not properly handled a file readability

### ISSUE THREAD

**Issue by derror** [frankykubo/gym_beam_exam#1] opened 2023-02-13 19:46 UTC
What if the file will not be readable for any reasons ? 

https://github.com/frankykubo/gym_beam_exam/blob/43db0d6a2c055ba0057d055f7dfff8bf51d1a23f/backends/php/src/analyze_sentiment.php#L13

**Comment by frankykubo** [comment] 2023-02-14 09:32
@derror Thanks for feedback, the issue is now fixed

**Closed by frankykubo** 2023-02-14 09:32 UTC
